### ISSUE TITLE
Да

### ISSUE THREAD

**Issue by Domaman202** [AlgorithmLX/AlgorithmLX#1]
Пошли на C учить буду кодить

**Comment by AlgorithmLX** [comment]
Научи С++

**Comment by Domaman202** [comment]
одумайся ради всего что можно

**Comment by AlgorithmLX** [comment]
Ладно

**Comment by HollowHorizon** [comment]
Может тогда сразу на Rust?

**Comment by AlgorithmLX** [comment]
> Может тогда сразу на Rust?

ХЭВАХВХВХАХВАХВХАХХВХАВАХВАВХА
TypeScript xD

**Comment by Domaman202** [comment]
украiнська мова?

**Comment by AlgorithmLX** [comment]
> украiнська мова?

Я скорее сдохну от смеха, пока учить буду, чем выучу

**Comment by Domaman202** [comment]
Iван Бандера
